### ISSUE TITLE
Not compatible with rack 2

### ISSUE THREAD

**Issue by dblock** [migrs/rack-server-pages#5]
Via https://github.com/slack-ruby/slack-ruby-bot-server/pull/31.

```
1) SlackRubyBotServer::Api returns a robots.txt that disallows indexing
     Failure/Error: get '/robots.txt'

     NoMethodError:
       undefined method `call' for nil:NilClass
       Did you mean?  caller
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-2.0.1/lib/rack/file.rb:31:in `call'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-server-pages-0.0.6/lib/rack/server_pages.rb:47:in `serving'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-server-pages-0.0.6/lib/rack/server_pages.rb:37:in `call'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # ./spec/api/robots_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./spec/support/database_cleaner.rb:15:in `block (3 levels) in <top (required)>'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/generic/base.rb:16:in `cleaning'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:98:in `cleaning'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # /Users/dblock/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/support/database_cleaner.rb:14:in `block (2 levels) in <top (required)>'
```

**Comment by dblock** [comment]
The problem is that Rack::File now has a [constructor](https://github.com/rack/rack/blob/master/lib/rack/file.rb#L22) that's not being called from StaticFile.

**Comment by rlue** [comment]
Thank you @dblock!

**Comment by dblock** [comment]
No word from @migrs so we haven't made much progress :(
